### ISSUE TITLE
unicode error while trying to emit output

### ISSUE THREAD

**Issue by eastein** [eastein/andrey#2]
```
(greetermon)eastein@freyr ~/git/andrey :) $ python markovbot.py irc.freenode.net greetermon \#pumpingstationone -r .009 -f ~/.andrey/greetermon.mpack
creating new irc connection
Traceback (most recent call last):
  File "markovbot.py", line 132, in <module>
    s.run()
  File "/home/eastein/venvs/greetermon/local/lib/python2.7/site-packages/mediorc/__init__.py", line 101, in run
    self.client.ircobj.process_once(0.2)
  File "/home/eastein/venvs/greetermon/local/lib/python2.7/site-packages/irc/client.py", line 244, in process_once
    self.process_data(i)
  File "/home/eastein/venvs/greetermon/local/lib/python2.7/site-packages/irc/client.py", line 201, in process_data
    c.process_data()
  File "/home/eastein/venvs/greetermon/local/lib/python2.7/site-packages/irc/client.py", line 575, in process_data
    self._process_line(line)
  File "/home/eastein/venvs/greetermon/local/lib/python2.7/site-packages/irc/client.py", line 646, in _process_line
    self._handle_event(event)
  File "/home/eastein/venvs/greetermon/local/lib/python2.7/site-packages/irc/client.py", line 669, in _handle_event
    self.manifold._handle_event(self, event)
  File "/home/eastein/venvs/greetermon/local/lib/python2.7/site-packages/irc/client.py", line 383, in _handle_event
    result = handler.callback(connection, event)
  File "/home/eastein/venvs/greetermon/local/lib/python2.7/site-packages/irc/client.py", line 1223, in _dispatcher
    method(connection, event)
  File "markovbot.py", line 74, in on_pubmsg
    r = self.m.choose(txt, continued=10)
  File "/home/eastein/git/andrey/andrey.py", line 133, in choose
    return self.detokenize(self._choose(*a, **kw))
  File "/home/eastein/git/andrey/andrey.py", line 138, in detokenize
    return ' '.join(list(tokens))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2: ordinal not in range(128)
```

**Comment by eastein** [comment]
[11 12:42:11] < loans> i bet the germans do
[11 12:42:12] >>> Signoff greetermon: #pumpingstationone (Remote host closed the connection)

Something chainable from that was the 'bad' data perhaps.

**Comment by eastein** [comment]
I'll see how this holds up in "production".
